In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

final_standing_table=[]
links=['https://www.goalzz.com/main.aspx?c=24721&stage=1&smonth=202209','https://www.goalzz.com/main.aspx?c=24721&stage=1&smonth=202210','https://www.goalzz.com/main.aspx?c=24721&stage=1&smonth=202211','https://www.goalzz.com/main.aspx?c=24721&stage=1&smonth=202212','https://www.goalzz.com/main.aspx?c=24721&stage=1&smonth=202301','https://www.goalzz.com/main.aspx?c=24721&stage=1&smonth=202302','https://www.goalzz.com/main.aspx?c=24721&stage=1&smonth=202303','https://www.goalzz.com/main.aspx?c=24721&stage=1&smonth=202304','https://www.goalzz.com/main.aspx?c=24721&stage=1&smonth=202305']

for j in range(0,len(links)):
    driver = webdriver.Chrome()
    driver.get(links[j])

    html = driver.page_source 
    driver.quit() 



    soup=BeautifulSoup(html)
    standing_table=soup.select('tr[data-match],td.match_date')
    date_index=[]
    for i in range(0,len(standing_table)):
        if str(standing_table[i]).startswith('<td'):
            standing_table[i]=standing_table[i].text
            date_index.append(i)

    for i in range(0,len(standing_table)):
        if i not in date_index:
            standing_table[i]=[standing_table[i].find('span').text[:5],standing_table[i].find_all('a', class_='tl')[0].text,standing_table[i].find('td', class_='sc').text,standing_table[i].find_all('a', class_='tl')[1].text,standing_table[i].find('td', class_='s').text]

    for i in range(0,len(standing_table)):
        if i in date_index:
            a=i
        if i not in date_index:
            standing_table[i].append(standing_table[a])

    for index in sorted(date_index, reverse=True):
        del standing_table[index]
    
    final_standing_table += standing_table
    
final_standing_table[:5]

[['20:30',
  'Renaissance de Berkane',
  '0 : 1',
  'Hassania Union Sport Agadir',
  'Week # 1',
  'Thursday 1 September 2022'],
 ['16:56',
  'Fath Union Sport de Rabat',
  '1 : 1',
  'Wydad Athletic Club',
  'Week # 1',
  'Friday 2 September 2022'],
 ['19:15',
  'Mouloudia Oujda',
  '0 : 1',
  'FAR Rabat',
  'Week # 1',
  'Friday 2 September 2022'],
 ['21:30',
  'Difaa Hassani El Jadidi',
  '1 : 0',
  'UTS Union Touarga Sport Rabat',
  'Week # 1',
  'Friday 2 September 2022'],
 ['18:00',
  'Ittihad Tanger',
  '0 : 1',
  'JSS Jeunesse Sportive Soualem',
  'Week # 1',
  'Saturday 3 September 2022']]

In [14]:
len(final_standing_table)

208

In [15]:
df = pd.DataFrame(final_standing_table, columns =['Time', 'Receiving team', 'Score', 'Guest team', 'Week','Date'])
df = df.iloc[:-1 , :].iloc[:-1 , :]
df

,Time,Receiving team,Score,Guest team,Week,Date
0,20:30,Renaissance de Berkane,0 : 1,Hassania Union Sport Agadir,Week # 1,Thursday 1 September 2022
1,16:56,Fath Union Sport de Rabat,1 : 1,Wydad Athletic Club,Week # 1,Friday 2 September 2022
2,19:15,Mouloudia Oujda,0 : 1,FAR Rabat,Week # 1,Friday 2 September 2022
3,21:30,Difaa Hassani El Jadidi,1 : 0,UTS Union Touarga Sport Rabat,Week # 1,Friday 2 September 2022
4,18:00,Ittihad Tanger,0 : 1,JSS Jeunesse Sportive Soualem,Week # 1,Saturday 3 September 2022
...,...,...,...,...,...,...
201,20:02,Maghreb de Fes,0 : 0,UTS Union Touarga Sport Rabat,Week # 26,Saturday 20 May 2023
202,20:01,Olympique Club De Khouribga,1 : 1,Difaa Hassani El Jadidi,Week # 26 Complexe OCPHome match1:2Home game s...,Sunday 21 May 2023
203,20:05,Ittihad Tanger,0 : 0,Raja Club Athletic,Week # 26 Stade de TangerHome match0:3Home gam...,Sunday 21 May 2023
204,20:00,Mouloudia Oujda,1 : 2,Renaissance de Berkane,Week # 26 Stade d'Honneur D'oujdaHome match0:2...,Sunday 21 May 2023
205,20:01,JSS Jeunesse Sportive Soualem,1 : 3,Chabab Mohammedia,Week # 26 Stade Arazi a BerrechidHome match3:0...,Sunday 21 May 2023

In [16]:
df['Week'][190]='Week # 24'
df['Week'][191]='Week # 24'
df['Week'][194]='Week # 25'
df['Week'][196]='Week # 25'
df['Week'][198]='Week # 25'
df['Week'][202]='Week # 26'
df['Week'][203]='Week # 26'
df['Week'][204]='Week # 26'
df['Week'][205]='Week # 26'
df.to_csv('Botola Data 2022 2023.csv')